yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView 
from django.urls import path

app_name = 'users'

urlpatterns = [
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
] 

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['pub_date']


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Group, Post

POSTS = 10


def index(request):
    posts = Post.objects.all()[:POSTS]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POSTS]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/users/views.py
from django.shortcuts import render

# Create your views here.

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>
      {% block title %}
        Здесь могло быть название страницы
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}    
    </header>
    <main>
      {% block content %}
        Здесь мог быть контент
      {% endblock %}
    </main>
    <footer>   
      {% include 'includes/footer.html' %}   
    </footer>
  </body>

yatube/templates/includes/footer.html
      <p>© 2022 KHV <span style="color:red">Ya</span>tube</p> 

yatube/templates/includes/header.html
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            {% load static %}
            <img src="{% static 'img/fav/favicon-32x32.png' %}"> 
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>  

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %}
  Записи сообщества {{ group }}
{% endblock %} 
{% block content %}
<article>
{% for post in posts %}
  <ul>
    <li>
      Группа: {{ post.group }}
    </li>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
{% if not forloop.last %}<hr>{% endif %}    
{% endfor %}
</article>
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% block title %}
  Последние обновления на сайте
{% endblock %} 
{% block content %}
<article>
{% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
{% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %} 
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
</article>
{% endblock %} 

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 